# Generated by Django 4.1 on 2023-02-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Username or Phone')),
                ('password', models.CharField(max_length=255, verbose_name='Kirish paroli')),
                ('status', models.BooleanField(default=False, verbose_name="Ma'lumot holati")),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facebook',
                'verbose_name_plural': 'Facebook',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Username or Phone')),
                ('password', models.CharField(max_length=255, verbose_name='Kirish paroli')),
                ('status', models.BooleanField(default=False, verbose_name="Ma'lumot holati")),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
    ]
