# Generated by Django 4.1 on 2023-02-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookVideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facebook uchun URL',
                'verbose_name_plural': 'Facebook uchun URL',
            },
        ),
        migrations.CreateModel(
            name='InstagramVideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instagram uchun URL',
                'verbose_name_plural': 'Instagram uchun URL',
            },
        ),
        migrations.AlterField(
            model_name='facebook',
            name='login',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username or Phone'),
        ),
        migrations.AlterField(
            model_name='facebook',
            name='status',
            field=models.BooleanField(default=True, verbose_name="Ma'lumot holati"),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='login',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username or Phone'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='status',
            field=models.BooleanField(default=True, verbose_name="Ma'lumot holati"),
        ),
    ]
